export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const PRODUCT_UPLOAD_REQUEST='PRODUCT_UPLOAD_REQUEST';
export const PRODUCT_UPLOAD_SUCCESS='PRODUCT_UPLOAD_SUCCESS';
export const PRODUCT_UPLOAD_FAIL='PRODUCT_UPLOAD_FAIL';
export const PRODUCT_UPLOAD_RESET='PRODUCT_UPLOAD_RESET';

export const PRODUCT_MINE_LIST_REQUEST = 'PRODUCT_MINE_LIST_REQUEST';
export const PRODUCT_MINE_LIST_SUCCESS = 'PRODUCT_MINE_LIST_SUCCESS';
export const PRODUCT_MINE_LIST_FAIL = 'PRODUCT_MINE_LIST_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';


export const USER_ADDRESS_MAP_CONFIRM = 'USER_ADDRESS_MAP_CONFIRM';

export const SAVE_PRODUCT_UPLOAD_DETAILS = 'SAVE_PRODUCT_UPLOAD_DETAILS';

